package com.giantLink.Hiring.recrutementservice.enums;

public enum PermissionEnum {
    CAMPAIGN_CREATE,
    CAMPAIGN_READ,
    CAMPAIGN_READ_BY_NAME,
    CAMPAIGN_READ_ALL,
    CAMPAIGN_UPDATE,
    CAMPAIGN_DELETE,

    CANDIDACY_CREATE,
    CANDIDACY_READ,
    CANDIDACY_READ_ALL,
    CANDIDACY_UPDATE,
    CANDIDACY_DELETE,

    CANDIDATE_CREATE,
    CANDIDATE_READ,
    CANDIDATE_READ_ALL,
    CANDIDATE_UPDATE,
    CANDIDATE_DELETE,

    CONTRACT_CREATE,
    CONTRACT_READ,
    CONTRACT_READ_ALL,
    CONTRACT_READ_BY_NAME,
    CONTRACT_UPDATE,
    CONTRACT_DELETE,

    CV_CREATE,
    CV_READ,
    CV_READ_ALL,
    CV_UPDATE,
    CV_DELETE,

    INTERVIEW_CREATE,
    INTERVIEW_READ,
    INTERVIEW_READ_ALL,
    INTERVIEW_UPDATE,
    INTERVIEW_DELETE,

    PERMISSION_READ,
    PERMISSION_READ_ALL,
    PERMISSION_UPDATE,
    PERMISSION_GRANT_TO_ROLE,
    PERMISSION_REMOVE_FROM_ROLE,

    POST_CREATE,
    POST_READ,
    POST_READ_ALL,
    POST_READ_POTENTIAL_CANDIDACIES,
    POST_UPDATE,
    POST_DELETE,

    QUALIFICATION_CREATE,
    QUALIFICATION_READ,
    QUALIFICATION_READ_ALL,
    QUALIFICATION_UPDATE,
    QUALIFICATION_DELETE,

    REGION_CREATE,
    REGION_READ,
    REGION_READ_ALL,
    REGION_UPDATE,
    REGION_DELETE,

    ROLE_CREATE,
    ROLE_READ,
    ROLE_READ_ALL,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_ADD_PERMISSION,
    ROLE_DELETE_PERMISSION,

    USER_CREATE,
    USER_READ,
    USER_READ_ALL,
    USER_UPDATE,
    USER_DELETE
}

