server:
  port: 2023
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      enabled: true
spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: rh-service
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/rh-service?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 2000000
      refresh-token:
          expiration: 3000000

